"""Render the default perf-sweep plot set as PNGs.

Nine default plots, all per-case grids — one subplot per case in
the order ``case_prod_regular_tide / case_prod_quadtree_subgrid_tide /
case_prod_riverine / case_prod_storm_amuv / case_prod_compound_snapwave``:

1. ``wall_vs_length.png``               — wall time vs simulation length.
2. ``per_step_vs_length.png``           — per-step gap ``U(L)/step_count`` (ms).
3. ``gpu_vs_cpu_speedup.png``           — ``<CPU_REFERENCE>_wall / gpu_n2_wall``.
4. ``component_breakdown.png``          — stacked named components at
   ``1x gpu_n2 4d`` for each case.
5. ``gpu_utilization.png``              — gpu_sm_p50 + p95 envelope.
6. ``gpu_saturation_vs_rank.png``       — per-case wall bars + SM%
   overlay, colored green/red by whether ``gpu_n<k+1> wall`` ≤ or > the
   prior rank's wall. Annotates UNDERLOADED when single-GPU SM% mean
   is below a configurable threshold.
7. ``omp_scaling.png``                  — wall vs cpu_n<k> threads (log-x),
   one line per length, per case. Skipped cells render as "x"
   markers at the projected position.
8. ``omp_efficiency.png``               — strong-scaling efficiency
   ``(cpu_n1_wall / k) / cpu_n<k>_wall`` vs threads (perfect = 1.0).
9. ``gpu_cpu_crossover_heatmap.png``    — heat map per case of
   ``cpu_n<k>_wall / gpu_n<g>_wall`` across ``k × g``. Cells > 1
   are CPU-faster; cells < 1 are GPU-faster.

When a comparison sweep is supplied (CLI ``--prior`` or env
``PRIOR_SWEEP``), each of the five also gets a paired "prior vs
current" PNG in the same directory (``*_compare.png``).

Defaults: outputs land in ``<sweep_dir>/plots/``. CLI:

    python -m tests.perf.analyze.plot --sweep <sweep_dir>
    python -m tests.perf.analyze.plot --sweep <sweep_dir> --prior <other>
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from . import load

DEFAULT_CASE_ORDER = (
    "case_prod_regular_tide",
    "case_prod_quadtree_subgrid_tide",
    "case_prod_riverine",
    "case_prod_storm_amuv",
    "case_prod_compound_snapwave",
)
LENGTHS = ("1h", "6h", "24h", "4d")
LENGTH_SECONDS = {"1h": 3600, "6h": 21600, "24h": 86400, "4d": 345600}

# Default CPU configuration used as the "CPU baseline" in cross-config
# comparisons (the line on wall_vs_length / per_step_vs_length and the
# denominator in gpu_vs_cpu_speedup / gpu_cpu_crossover_heatmap, and the
# CPU column generated by compare.py). Selected as the OpenMP knee on
# the production host per SOR-1025 (the EPYC 7C13's second SMT thread
# per core anti-scales for SFINCS, so cpu_n128 is consistently slower
# than cpu_n64 — see tests/perf/perf-full-20260519/SUMMARY.md). The
# OpenMP scaling plot still spans n1..n128; only the SCALAR CPU
# baseline used in cross-config comparisons changes. Flip this
# constant if a future host has a different SMT geometry.
CPU_REFERENCE = "cpu_n64"

CONFIG_COLORS = {
    CPU_REFERENCE: "#4C72B0",  # blue
    "gpu_n1": "#DD8452",       # orange
    "gpu_n2": "#55A467",       # green
}
CONFIG_LABEL = {CPU_REFERENCE: CPU_REFERENCE, "gpu_n1": "gpu_n1", "gpu_n2": "gpu_n2"}

# Saturation-panel colors — encode the helpful/hurtful direction of
# the rank-count increment. Used by plot_gpu_saturation.
SATURATION_BAR_GREEN = "#2CA02C"  # adding ranks helps (or baseline)
SATURATION_BAR_RED = "#C44E52"    # adding ranks hurts

COMPONENT_COLORS = {
    "boundaries": "#4C72B0",
    "momentum": "#DD8452",
    "continuity": "#55A467",
    "snapwave": "#C44E52",
    "meteo": "#8172B2",
    "output": "#937860",
    "U_L": "#CCB974",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _cases_in(df: pd.DataFrame) -> tuple[str, ...]:
    """Return cases present in df, preserving DEFAULT_CASE_ORDER where possible."""
    present = set(df["case"].dropna().unique())
    ordered = [c for c in DEFAULT_CASE_ORDER if c in present]
    extras = sorted(present - set(ordered))
    return tuple(ordered + extras)


def _series(df: pd.DataFrame, case: str, grid: str, config: str, column: str):
    """Return (x_seconds_array, y_values_array) for plotting."""
    sub = df[(df["case"] == case) & (df["grid"] == grid) & (df["config"] == config)]
    sub = sub.dropna(subset=["length"])
    xs, ys = [], []
    for L in LENGTHS:
        rows = sub[sub["length"] == L]
        if rows.empty:
            continue
        val = rows.iloc[0][column]
        if val != val:  # NaN
            continue
        xs.append(LENGTH_SECONDS[L])
        ys.append(float(val))
    return np.array(xs), np.array(ys)


def _figure_subtitle(env_text: str) -> str:
    """One-line capture-environment summary for figure subtitle."""
    if not env_text:
        return ""
    cpu = gpu = head = ""
    for raw in env_text.splitlines():
        line = raw.strip()
        if line.startswith("host CPU"):
            cpu = line.split(":", 1)[1].strip()
        elif line.startswith("host GPU"):
            gpu = line.split(":", 1)[1].strip()
        elif line.startswith("HEAD"):
            head = line.split(":", 1)[1].strip()
    pieces = []
    if cpu:
        pieces.append(f"CPU={cpu}")
    if gpu:
        pieces.append(f"GPU={gpu}")
    if head:
        pieces.append(f"HEAD={head}")
    return "  |  ".join(pieces)


def _layout(n_cases: int) -> tuple[int, int, tuple[int, int]]:
    """Return (nrows, ncols, figsize) for a per-case subplot grid."""
    if n_cases <= 3:
        return 1, n_cases, (5 * n_cases, 4)
    if n_cases <= 6:
        return 2, 3, (15, 8)
    rows = (n_cases + 2) // 3
    return rows, 3, (15, 4 * rows)


def _add_title(fig, title: str, subtitle: str) -> None:
    if subtitle:
        fig.suptitle(title + "\n" + subtitle, fontsize=12, y=0.995)
    else:
        fig.suptitle(title, fontsize=12, y=0.995)


def _save(fig, path: Path) -> None:
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(path, dpi=120)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Individual plot builders
# ---------------------------------------------------------------------------

def _plot_metric_per_case(
    df: pd.DataFrame,
    title: str,
    ylabel: str,
    column: str,
    subtitle: str,
    out_path: Path,
    yscale: str = "log",
    transform=None,
) -> None:
    """Per-case 5-subplot grid plotting ``column`` for each (config, grid)."""
    cases = _cases_in(df)
    if not cases:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        for config in (CPU_REFERENCE, "gpu_n1", "gpu_n2"):
            for grid, style in (("1x", "-"), ("4x", "--")):
                xs, ys = _series(df, case, grid, config, column)
                if len(xs) == 0:
                    continue
                ys_plot = transform(ys) if transform else ys
                label = f"{CONFIG_LABEL[config]} ({grid})"
                ax.plot(
                    xs, ys_plot,
                    marker="o", linestyle=style,
                    color=CONFIG_COLORS[config],
                    label=label,
                )
        ax.set_xscale("log")
        if yscale == "log":
            ax.set_yscale("log")
        ax.set_xticks([LENGTH_SECONDS[L] for L in LENGTHS])
        ax.set_xticklabels(LENGTHS)
        ax.set_xlabel("simulation length")
        ax.set_ylabel(ylabel)
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=8)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, title, subtitle)
    _save(fig, out_path)


def plot_wall_vs_length(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    _plot_metric_per_case(
        df,
        title=f"Wall time vs simulation length — {label}",
        ylabel="wall time (s)",
        column="wall",
        subtitle=subtitle,
        out_path=out_path,
        yscale="log",
    )


def plot_per_step_vs_length(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    _plot_metric_per_case(
        df,
        title=f"Per-step unaccounted gap vs simulation length — {label}",
        ylabel="per_step = U(L)/step_count (ms)",
        column="per_step",
        subtitle=subtitle,
        out_path=out_path,
        yscale="linear",
        transform=lambda ys: ys * 1000.0,
    )


def compute_gpu_vs_cpu_speedup(
    df: pd.DataFrame,
    case: str,
    grid: str,
    cpu_config: str = CPU_REFERENCE,
    gpu_config: str = "gpu_n2",
) -> tuple[list[int], np.ndarray]:
    """Return ``(length_seconds, speedup)`` for a (case, grid) cell.

    The speedup is ``cpu_config_wall / gpu_config_wall`` evaluated at
    each shared simulation length. Lengths with no measurement on
    either side are dropped. The CPU denominator defaults to the
    module-level ``CPU_REFERENCE`` so a future host with a different
    SMT geometry only needs to flip one constant.
    """
    xs_cpu, ys_cpu = _series(df, case, grid, cpu_config, "wall")
    xs_gpu, ys_gpu = _series(df, case, grid, gpu_config, "wall")
    if len(xs_cpu) == 0 or len(xs_gpu) == 0:
        return [], np.array([])
    cpu_map = dict(zip(xs_cpu.tolist(), ys_cpu.tolist()))
    gpu_map = dict(zip(xs_gpu.tolist(), ys_gpu.tolist()))
    shared = sorted(set(cpu_map) & set(gpu_map))
    if not shared:
        return [], np.array([])
    speedup = np.array([
        cpu_map[s] / gpu_map[s] if gpu_map[s] > 0 else np.nan
        for s in shared
    ])
    return shared, speedup


def plot_gpu_vs_cpu_speedup(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """y = ``CPU_REFERENCE``_wall / gpu_n2_wall per case; crossover where line > 1."""
    cases = _cases_in(df)
    if not cases:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        for grid, style in (("1x", "-"), ("4x", "--")):
            shared, speedup = compute_gpu_vs_cpu_speedup(df, case, grid)
            if not shared:
                continue
            ax.plot(
                shared, speedup,
                marker="o", linestyle=style,
                color="#000000",
                label=f"{grid} grid",
            )
        ax.axhline(1.0, color="red", linestyle=":", alpha=0.5)
        ax.set_xscale("log")
        ax.set_xticks([LENGTH_SECONDS[L] for L in LENGTHS])
        ax.set_xticklabels(LENGTHS)
        ax.set_xlabel("simulation length")
        ax.set_ylabel(f"speedup ({CPU_REFERENCE} / gpu_n2)")
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=8)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, f"GPU vs CPU speedup vs simulation length — {label}", subtitle)
    _save(fig, out_path)


def plot_component_breakdown(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """Stacked-bar named components at 1x gpu_n2 4d per case."""
    cases = _cases_in(df)
    if not cases:
        return
    keys = ("boundaries", "momentum", "continuity", "snapwave", "meteo", "output", "U_L")

    fig, ax = plt.subplots(figsize=(max(8, 1.6 * len(cases)), 5))
    x = np.arange(len(cases))
    bottoms = np.zeros(len(cases))
    for key in keys:
        vals = []
        for case in cases:
            row = df[
                (df["case"] == case)
                & (df["grid"] == "1x")
                & (df["length"] == "4d")
                & (df["config"] == "gpu_n2")
            ]
            if row.empty:
                vals.append(0.0)
                continue
            v = row.iloc[0][key]
            vals.append(0.0 if v != v else float(v))
        vals_arr = np.array(vals)
        ax.bar(
            x, vals_arr, bottom=bottoms,
            label=key,
            color=COMPONENT_COLORS[key],
            edgecolor="white", linewidth=0.5,
        )
        bottoms = bottoms + vals_arr
    ax.set_xticks(x)
    ax.set_xticklabels([c.replace("case_prod_", "") for c in cases], rotation=20, ha="right")
    ax.set_ylabel("time (s)")
    ax.set_title("Named-component breakdown at 1x gpu_n2 4d", fontsize=10)
    ax.legend(loc="best", fontsize=8)
    ax.grid(True, axis="y", alpha=0.3)
    _add_title(fig, f"Component breakdown — {label}", subtitle)
    _save(fig, out_path)


def plot_gpu_utilization(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """gpu_sm_p50 + p95 envelope vs simulation length, per case."""
    cases = _cases_in(df)
    if not cases:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        for config in ("gpu_n1", "gpu_n2"):
            for grid, style in (("1x", "-"), ("4x", "--")):
                xs_p50, ys_p50 = _series(df, case, grid, config, "gpu_sm_p50")
                xs_p95, ys_p95 = _series(df, case, grid, config, "gpu_sm_p95")
                if len(xs_p50) == 0:
                    continue
                ax.plot(
                    xs_p50, ys_p50,
                    marker="o", linestyle=style,
                    color=CONFIG_COLORS[config],
                    label=f"{config} p50 ({grid})",
                )
                if len(xs_p95) == len(xs_p50):
                    ax.fill_between(
                        xs_p50, ys_p50, ys_p95,
                        color=CONFIG_COLORS[config], alpha=0.15,
                    )
        ax.set_xscale("log")
        ax.set_xticks([LENGTH_SECONDS[L] for L in LENGTHS])
        ax.set_xticklabels(LENGTHS)
        ax.set_ylim(0, 100)
        ax.set_xlabel("simulation length")
        ax.set_ylabel("GPU sm %")
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=8)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, f"GPU utilization (sm %) — {label}", subtitle)
    _save(fig, out_path)


# ---------------------------------------------------------------------------
# OpenMP scaling / efficiency / GPU-CPU crossover
# ---------------------------------------------------------------------------

LENGTH_COLORS = {
    "1h": "#4C72B0",
    "6h": "#DD8452",
    "24h": "#55A467",
    "4d": "#C44E52",
}


def _cpu_thread_counts(df: pd.DataFrame) -> list[int]:
    """Return the sorted list of k values from cpu_n<k> configs present."""
    out: set[int] = set()
    for cfg in df["config"].dropna().unique():
        if isinstance(cfg, str) and cfg.startswith("cpu_n"):
            try:
                out.add(int(cfg[len("cpu_n"):]))
            except ValueError:
                continue
    return sorted(out)


def _gpu_rank_counts(df: pd.DataFrame) -> list[int]:
    """Return the sorted list of g values from gpu_n<g> configs present."""
    out: set[int] = set()
    for cfg in df["config"].dropna().unique():
        if isinstance(cfg, str) and cfg.startswith("gpu_n"):
            try:
                out.add(int(cfg[len("gpu_n"):]))
            except ValueError:
                continue
    return sorted(out)


def _cpu_wall_at_k(df: pd.DataFrame, case: str, grid: str, length: str, k: int):
    """Return (wall, skipped_estimated_min) for one (case, grid, length, cpu_n<k>)."""
    row = df[
        (df["case"] == case)
        & (df["grid"] == grid)
        & (df["length"] == length)
        & (df["config"] == f"cpu_n{k}")
    ]
    if row.empty:
        return (float("nan"), float("nan"))
    r = row.iloc[0]
    return (float(r["wall"]) if r["wall"] == r["wall"] else float("nan"),
            float(r["skipped_estimated_wall"])
                if r["skipped_estimated_wall"] == r["skipped_estimated_wall"]
                else float("nan"))


def plot_omp_scaling(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """Wall time vs cpu_n<k> threads, log-x, one line per length, per case.

    Skipped cells render as "x" markers at the projected position so
    the operator can see "skipped — projected > budget" alongside
    measured points. The OpenMP knee (smallest k beyond which adding
    threads stops halving wall) is highlighted with a vertical
    dashed line per case.
    """
    cases = _cases_in(df)
    ks = _cpu_thread_counts(df)
    if not cases or not ks:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        knee_marker = None
        for L in LENGTHS:
            xs_run: list[int] = []
            ys_run: list[float] = []
            xs_skip: list[int] = []
            ys_skip: list[float] = []
            for k in ks:
                wall, skipped_min = _cpu_wall_at_k(df, case, "1x", L, k)
                if wall == wall:
                    xs_run.append(k)
                    ys_run.append(wall)
                elif skipped_min == skipped_min:
                    xs_skip.append(k)
                    ys_skip.append(skipped_min * 60.0)  # min → s
            if xs_run:
                ax.plot(
                    xs_run, ys_run, marker="o", linestyle="-",
                    color=LENGTH_COLORS.get(L, "#000"),
                    label=f"{L} measured",
                )
            if xs_skip:
                ax.plot(
                    xs_skip, ys_skip, marker="x", linestyle=":",
                    color=LENGTH_COLORS.get(L, "#000"), alpha=0.6,
                    label=f"{L} projected",
                )
            # Knee detection — smallest k where doubling k yields <
            # 30% wall reduction. Only computed for the longest length
            # whose curve is complete enough to detect.
            if L == "4d" and len(xs_run) >= 2:
                pairs = sorted(zip(xs_run, ys_run))
                for j in range(len(pairs) - 1):
                    k_lo, w_lo = pairs[j]
                    k_hi, w_hi = pairs[j + 1]
                    if k_hi >= 2 * k_lo and w_lo > 0 and (w_lo - w_hi) / w_lo < 0.3:
                        knee_marker = k_lo
                        break
        if knee_marker is not None:
            ax.axvline(knee_marker, color="#888", linestyle="--", alpha=0.7,
                       label=f"knee @ k={knee_marker}")
        ax.set_xscale("log", base=2)
        ax.set_yscale("log")
        ax.set_xticks(ks)
        ax.set_xticklabels([str(k) for k in ks])
        ax.set_xlabel("OMP_NUM_THREADS")
        ax.set_ylabel("wall time (s)")
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=7, ncol=2)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, f"OpenMP scaling (wall vs threads, 1x grid) — {label}", subtitle)
    _save(fig, out_path)


def plot_omp_efficiency(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """Strong-scaling efficiency: ``(cpu_n1_wall / k) / cpu_n<k>_wall``.

    Perfect parallelism = 1.0. Deviations < 1.0 indicate parallelism
    overhead / contention. Per case, one line per length.

    When cpu_n1 was skipped at a given length, fall back to the
    smallest measured k as the reference and scale accordingly:
    efficiency = (ref_wall * ref_k / k) / cpu_n<k>_wall.
    """
    cases = _cases_in(df)
    ks = _cpu_thread_counts(df)
    if not cases or not ks:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        for L in LENGTHS:
            ref_wall = float("nan")
            ref_k = 0
            for k in ks:
                wall, _ = _cpu_wall_at_k(df, case, "1x", L, k)
                if wall == wall:
                    ref_wall = wall
                    ref_k = k
                    break
            if not (ref_wall == ref_wall):
                continue
            xs: list[int] = []
            ys: list[float] = []
            for k in ks:
                wall, _ = _cpu_wall_at_k(df, case, "1x", L, k)
                if not (wall == wall) or wall <= 0:
                    continue
                eff = (ref_wall * ref_k / k) / wall
                xs.append(k)
                ys.append(eff)
            if xs:
                ax.plot(
                    xs, ys, marker="o", linestyle="-",
                    color=LENGTH_COLORS.get(L, "#000"),
                    label=f"{L} (ref k={ref_k})",
                )
        ax.axhline(1.0, color="red", linestyle=":", alpha=0.5, label="ideal")
        ax.set_xscale("log", base=2)
        ax.set_xticks(ks)
        ax.set_xticklabels([str(k) for k in ks])
        ax.set_xlabel("OMP_NUM_THREADS")
        ax.set_ylabel("efficiency (ref_wall · ref_k / k) / wall_k")
        ax.set_ylim(0, max(1.2, ax.get_ylim()[1] if ax.get_ylim()[1] > 1.2 else 1.2))
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=7)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, f"OpenMP strong-scaling efficiency (1x grid, 4d unless otherwise) — {label}", subtitle)
    _save(fig, out_path)


def plot_gpu_cpu_crossover_heatmap(df: pd.DataFrame, label: str, subtitle: str, out_path: Path) -> None:
    """Per-case heat map of ``cpu_n<k>_wall / gpu_n<g>_wall``.

    One subplot per case; one row per cpu_n<k> (sorted ascending),
    one column per gpu_n<g>. Cells > 1 (red-ish) are CPU-faster;
    cells < 1 (blue-ish) are GPU-faster. The boundary line (ratio
    = 1) is the crossover. Built from the 4d-length rows — the
    longest length is the one operators care about for "is the
    crossover threshold k still useful as the run grows?"
    """
    cases = _cases_in(df)
    ks = _cpu_thread_counts(df)
    gs = _gpu_rank_counts(df)
    if not cases or not ks or not gs:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    cmap = plt.get_cmap("RdBu_r")

    # Use the longest available length per case (4d if present).
    def _length_for(case: str) -> str | None:
        for L in reversed(LENGTHS):
            row = df[
                (df["case"] == case)
                & (df["grid"] == "1x")
                & (df["length"] == L)
                & (df["config"] == f"gpu_n{gs[0]}")
            ]
            if not row.empty and row.iloc[0]["wall"] == row.iloc[0]["wall"]:
                return L
        return None

    for i, case in enumerate(cases):
        ax = flat[i]
        L = _length_for(case)
        if L is None:
            ax.axis("off")
            ax.set_title(f"{case}\n(no gpu data)", fontsize=10)
            continue
        mat = np.full((len(ks), len(gs)), np.nan, dtype=float)
        for ri, k in enumerate(ks):
            cpu_wall, _ = _cpu_wall_at_k(df, case, "1x", L, k)
            for ci, g in enumerate(gs):
                row = df[
                    (df["case"] == case)
                    & (df["grid"] == "1x")
                    & (df["length"] == L)
                    & (df["config"] == f"gpu_n{g}")
                ]
                if row.empty:
                    continue
                gpu_wall = float(row.iloc[0]["wall"])
                if not (cpu_wall == cpu_wall) or not (gpu_wall == gpu_wall) or gpu_wall <= 0:
                    continue
                mat[ri, ci] = cpu_wall / gpu_wall
        # log-scale ratio for symmetric color centering at 1.0
        with np.errstate(invalid="ignore", divide="ignore"):
            log_mat = np.log2(mat)
        vmax = np.nanmax(np.abs(log_mat)) if np.any(np.isfinite(log_mat)) else 1.0
        if vmax <= 0:
            vmax = 1.0
        im = ax.imshow(
            log_mat, aspect="auto", origin="lower",
            cmap=cmap, vmin=-vmax, vmax=vmax,
        )
        ax.set_xticks(range(len(gs)))
        ax.set_xticklabels([f"gpu_n{g}" for g in gs])
        ax.set_yticks(range(len(ks)))
        ax.set_yticklabels([f"cpu_n{k}" for k in ks])
        ax.set_xlabel("GPU config")
        ax.set_ylabel("CPU config")
        ax.set_title(f"{case} ({L})", fontsize=10)
        # Annotate each cell with the linear ratio.
        for ri in range(len(ks)):
            for ci in range(len(gs)):
                v = mat[ri, ci]
                if v == v:
                    txt = f"{v:.2f}"
                    color = "white" if abs(log_mat[ri, ci]) > vmax * 0.5 else "black"
                    ax.text(ci, ri, txt, ha="center", va="center", color=color, fontsize=7)
                else:
                    ax.text(ci, ri, "—", ha="center", va="center", color="#888", fontsize=7)
        fig.colorbar(im, ax=ax, label="log2(cpu/gpu)", fraction=0.05)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(
        fig,
        f"GPU vs CPU crossover heatmap — {label}\n"
        "ratio = cpu_n<k>_wall / gpu_n<g>_wall  (>1 CPU-faster, <1 GPU-faster)",
        subtitle,
    )
    _save(fig, out_path)


# ---------------------------------------------------------------------------
# GPU saturation vs rank count (SOR-1037)
# ---------------------------------------------------------------------------

def _longest_length_with(df: pd.DataFrame, case: str, grid: str, config: str) -> str | None:
    """Return the longest measured length for a (case, grid, config) cell, or None."""
    for L in reversed(LENGTHS):
        row = df[
            (df["case"] == case)
            & (df["grid"] == grid)
            & (df["length"] == L)
            & (df["config"] == config)
        ]
        if not row.empty:
            w = row.iloc[0]["wall"]
            if w == w:
                return L
    return None


def _row_for(df: pd.DataFrame, case: str, grid: str, length: str, config: str):
    sub = df[
        (df["case"] == case)
        & (df["grid"] == grid)
        & (df["length"] == length)
        & (df["config"] == config)
    ]
    if sub.empty:
        return None
    return sub.iloc[0]


def compute_gpu_saturation_panel(
    df: pd.DataFrame,
    sm_threshold_pct: float = 30.0,
) -> list[dict]:
    """Build per-(case, grid) saturation metadata for the GPU rank panel.

    For each (case, grid) combo where at least two ``gpu_n<k>`` configs
    have a measured wall time at some shared longest length, emit one
    entry containing:

    - ``case``, ``grid``, ``length``
    - ``rank_counts``: sorted ``[k1, k2, ...]`` for the gpu_n<k> configs present
    - ``walls``: aligned list of wall times (s) at the longest length
    - ``sms``: aligned list of SM% (gpu_sm_p50) means at the longest length
    - ``bar_colors``: aligned list of helpful/hurtful color hex codes:
      green when ``walls[i] <= walls[i-1]`` (or for ``i == 0``, baseline),
      red when ``walls[i] > walls[i-1]``
    - ``underloaded``: True when ``sms[0] < sm_threshold_pct``
    - ``best_config``, ``best_wall``, ``next_best_config``,
      ``delta_vs_next_best`` (seconds; positive means best is faster than next)

    The plot driver and the SUMMARY recommendation section share this
    helper so they cannot drift on what counts as helpful, hurtful, or
    underloaded.
    """
    out: list[dict] = []
    gs = _gpu_rank_counts(df)
    if len(gs) < 2:
        return out

    cases = _cases_in(df)
    grids = sorted(df["grid"].dropna().unique().tolist())
    for case in cases:
        for grid in grids:
            # The shared longest length must have wall measured for
            # EVERY rank count we want to compare. Pick the longest
            # length where all gs[*] are measured; fall back to the
            # longest length where the first two are measured.
            measured_lengths_per_g = {
                g: _longest_length_with(df, case, grid, f"gpu_n{g}") for g in gs
            }
            # Need at least gs[0] and gs[1] measured.
            if not measured_lengths_per_g.get(gs[0]) or not measured_lengths_per_g.get(gs[1]):
                continue
            # Use the shortest of those longest-lengths so all configs
            # have data at the chosen length.
            available_lengths = [v for v in measured_lengths_per_g.values() if v]
            length = min(available_lengths, key=lambda L: LENGTH_SECONDS[L])
            # Collect rows at that length.
            ranks: list[int] = []
            walls: list[float] = []
            sms: list[float] = []
            for g in gs:
                row = _row_for(df, case, grid, length, f"gpu_n{g}")
                if row is None:
                    continue
                w = row["wall"]
                if not (w == w):
                    continue
                ranks.append(g)
                walls.append(float(w))
                sm = row["gpu_sm_p50"]
                sms.append(float(sm) if sm == sm else float("nan"))
            if len(ranks) < 2:
                continue

            # Bar colors. Baseline is green; subsequent bars green if
            # wall[i] <= wall[i-1] (helpful), red otherwise (hurtful).
            colors = [SATURATION_BAR_GREEN]
            for i in range(1, len(walls)):
                if walls[i] <= walls[i - 1]:
                    colors.append(SATURATION_BAR_GREEN)
                else:
                    colors.append(SATURATION_BAR_RED)

            # Best config = wall-time minimum.
            best_idx = int(np.argmin(walls))
            best_config = f"gpu_n{ranks[best_idx]}"
            # Next-best = second-smallest wall.
            order = sorted(range(len(walls)), key=lambda j: walls[j])
            next_idx = order[1]
            next_best_config = f"gpu_n{ranks[next_idx]}"
            delta = walls[next_idx] - walls[best_idx]

            underloaded = sms[0] == sms[0] and sms[0] < sm_threshold_pct

            out.append({
                "case": case,
                "grid": grid,
                "length": length,
                "rank_counts": ranks,
                "walls": walls,
                "sms": sms,
                "bar_colors": colors,
                "underloaded": bool(underloaded),
                "best_config": best_config,
                "best_wall": walls[best_idx],
                "best_sm": sms[best_idx],
                "next_best_config": next_best_config,
                "next_best_wall": walls[next_idx],
                "delta_vs_next_best": delta,
                "sm_threshold_pct": sm_threshold_pct,
            })
    return out


def plot_gpu_saturation(
    df: pd.DataFrame,
    out_dir: str | os.PathLike,
    sm_threshold_pct: float = 30.0,
    label: str = "",
    subtitle: str = "",
) -> Path | None:
    """Render the GPU saturation vs rank-count panel.

    One subplot per (case, grid) with at least two ``gpu_n<k>`` configs
    measured at the same longest available length. Each subplot draws:

    - Left Y axis: a wall-time bar per rank count (linear scale).
      Bar colors encode the rank-count increment direction —
      ``SATURATION_BAR_GREEN`` when ``gpu_n<k+1> wall <= gpu_n<k> wall``
      (helpful, ``gpu_n1`` is baseline-green), ``SATURATION_BAR_RED``
      when greater (hurtful). The red-vs-green encoding is the at-a-glance
      "is adding another GPU rank a win or a loss for this case?" signal.
    - Right Y axis: ``gpu_n1`` SM% (p50) overlay as a small grey bar.
      The subplot gets an "UNDERLOADED — n2 adds overhead without compute
      payoff" annotation when ``sms[0] < sm_threshold_pct``.
    - Per-subplot title carries the best-config recommendation
      ("best: gpu_n1" or "best: gpu_n2") based on the actual wall-time
      minimum in the data.

    The default ``sm_threshold_pct=30`` is a heuristic: GPU
    streaming-multiprocessor utilization below one-third typically
    indicates the kernel isn't keeping the SMs busy at single-GPU,
    so adding another rank tends to introduce halo-exchange overhead
    without a proportional compute payoff. The chosen default is not
    a perfect predictor — some workloads have low SM% but heavy
    per-step compute that DOES amortize across ranks (riverine,
    storm_amuv in the post-SOR-1019 sweep) — so the threshold is a
    function parameter callers can tune for their specific capture.

    Returns the written PNG path, or None when the sweep has no
    eligible (case, grid) combos.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "gpu_saturation_vs_rank.png"

    entries = compute_gpu_saturation_panel(df, sm_threshold_pct=sm_threshold_pct)
    if not entries:
        return None

    nrows, ncols, figsize = _layout(len(entries))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, entry in enumerate(entries):
        ax = flat[i]
        ranks = entry["rank_counts"]
        walls = entry["walls"]
        sms = entry["sms"]
        colors = entry["bar_colors"]
        x = np.arange(len(ranks))
        ax.bar(
            x, walls, width=0.55, color=colors,
            edgecolor="black", linewidth=0.5,
        )
        # Annotate wall time on top of each bar for legibility.
        ymax = max(walls) if walls else 1.0
        for j, (w, c) in enumerate(zip(walls, colors)):
            tag = "helpful" if c == SATURATION_BAR_GREEN else "hurtful"
            if j == 0:
                tag = "baseline"
            ax.text(j, w + 0.02 * ymax, f"{w:.1f}s\n({tag})",
                    ha="center", va="bottom", fontsize=7)
        ax.set_xticks(x)
        ax.set_xticklabels([f"gpu_n{g}" for g in ranks])
        ax.set_xlabel("rank count")
        ax.set_ylabel("wall time (s)")
        ax.set_ylim(0, ymax * 1.25)
        ax.grid(True, axis="y", alpha=0.3)

        # Right Y: SM% (p50) overlay.
        ax2 = ax.twinx()
        sm_x = x + 0.28
        # Replace NaN with 0 for plotting (and skip the annotation).
        sm_plot = [s if s == s else 0.0 for s in sms]
        ax2.bar(
            sm_x, sm_plot, width=0.15,
            color="#666666", alpha=0.75, edgecolor="black", linewidth=0.3,
            label="SM% (p50)",
        )
        ax2.set_ylim(0, 100)
        ax2.set_ylabel("GPU SM% (p50)")

        # Title: case [grid] | best: gpu_nK | length
        grid_suffix = f" [{entry['grid']}]" if entry["grid"] != "1x" else ""
        ax.set_title(
            f"{entry['case']}{grid_suffix}  |  best: {entry['best_config']}  "
            f"({entry['length']})",
            fontsize=9,
        )

        # UNDERLOADED annotation.
        if entry["underloaded"]:
            n1_sm = sms[0]
            ax.text(
                0.5, 0.94,
                "UNDERLOADED — n2 adds overhead without compute payoff\n"
                f"(SM%={n1_sm:.0f} < threshold={sm_threshold_pct:.0f})",
                transform=ax.transAxes, ha="center", va="top",
                fontsize=7, color=SATURATION_BAR_RED,
                bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                          edgecolor=SATURATION_BAR_RED, alpha=0.9),
            )

    for j in range(len(entries), nrows * ncols):
        flat[j].axis("off")

    title = "GPU saturation vs rank count"
    if label:
        title = f"{title} — {label}"
    _add_title(fig, title, subtitle)
    _save(fig, out_path)
    return out_path


# ---------------------------------------------------------------------------
# Compare-prior overlays
# ---------------------------------------------------------------------------

def _compare_metric_per_case(
    df_cur: pd.DataFrame, df_prior: pd.DataFrame,
    label_cur: str, label_prior: str,
    title: str, ylabel: str, column: str,
    subtitle: str, out_path: Path,
    yscale: str = "log",
    transform=None,
) -> None:
    cases = sorted(set(_cases_in(df_cur)) | set(_cases_in(df_prior)),
                   key=lambda c: DEFAULT_CASE_ORDER.index(c) if c in DEFAULT_CASE_ORDER else 99)
    if not cases:
        return
    nrows, ncols, figsize = _layout(len(cases))
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat = axes.flatten()
    for i, case in enumerate(cases):
        ax = flat[i]
        for tag, frame, line_alpha in (("current", df_cur, 1.0), ("prior", df_prior, 0.55)):
            for config in (CPU_REFERENCE, "gpu_n1", "gpu_n2"):
                xs, ys = _series(frame, case, "1x", config, column)
                if len(xs) == 0:
                    continue
                ys_plot = transform(ys) if transform else ys
                ax.plot(
                    xs, ys_plot,
                    marker="o" if tag == "current" else "x",
                    linestyle="-" if tag == "current" else ":",
                    color=CONFIG_COLORS[config],
                    alpha=line_alpha,
                    label=f"{config} {tag}",
                )
        ax.set_xscale("log")
        if yscale == "log":
            ax.set_yscale("log")
        ax.set_xticks([LENGTH_SECONDS[L] for L in LENGTHS])
        ax.set_xticklabels(LENGTHS)
        ax.set_xlabel("simulation length")
        ax.set_ylabel(ylabel)
        ax.set_title(case, fontsize=10)
        ax.grid(True, which="both", alpha=0.3)
        if i == 0:
            ax.legend(loc="best", fontsize=7, ncol=2)
    for j in range(len(cases), nrows * ncols):
        flat[j].axis("off")
    _add_title(fig, f"{title} — current={label_cur} vs prior={label_prior}", subtitle)
    _save(fig, out_path)


# ---------------------------------------------------------------------------
# Top-level driver
# ---------------------------------------------------------------------------

def render(
    sweep_dir: str | os.PathLike,
    prior_sweep_dir: str | os.PathLike | None = None,
    out_dir: str | os.PathLike | None = None,
) -> list[Path]:
    """Render the default plot set for a sweep directory.

    Returns the list of PNG paths written.
    """
    sweep = Path(sweep_dir)
    df = load.load_sweep(sweep)
    label = load.sweep_label(sweep)
    subtitle = _figure_subtitle(load.capture_env(sweep))

    if out_dir is None:
        out_dir = sweep / "plots"
    plots_dir = Path(out_dir)
    plots_dir.mkdir(parents=True, exist_ok=True)

    paths: list[Path] = []

    p = plots_dir / "wall_vs_length.png"
    plot_wall_vs_length(df, label, subtitle, p); paths.append(p)

    p = plots_dir / "per_step_vs_length.png"
    plot_per_step_vs_length(df, label, subtitle, p); paths.append(p)

    p = plots_dir / "gpu_vs_cpu_speedup.png"
    plot_gpu_vs_cpu_speedup(df, label, subtitle, p); paths.append(p)

    p = plots_dir / "component_breakdown.png"
    plot_component_breakdown(df, label, subtitle, p); paths.append(p)

    p = plots_dir / "gpu_utilization.png"
    plot_gpu_utilization(df, label, subtitle, p); paths.append(p)

    # GPU saturation vs rank count — rendered when at least two
    # gpu_n<k> rank counts are present in the sweep.
    if len(_gpu_rank_counts(df)) >= 2:
        sat = plot_gpu_saturation(df, plots_dir, label=label, subtitle=subtitle)
        if sat is not None:
            paths.append(sat)

    # OpenMP scaling / efficiency / GPU-vs-CPU crossover — rendered
    # only when the sweep carries a CPU thread-count axis (cpu_n<k>
    # for k != 128). Sweeps captured before SOR-1025 skip these.
    if len(_cpu_thread_counts(df)) >= 2:
        p = plots_dir / "omp_scaling.png"
        plot_omp_scaling(df, label, subtitle, p); paths.append(p)

        p = plots_dir / "omp_efficiency.png"
        plot_omp_efficiency(df, label, subtitle, p); paths.append(p)

        if _gpu_rank_counts(df):
            p = plots_dir / "gpu_cpu_crossover_heatmap.png"
            plot_gpu_cpu_crossover_heatmap(df, label, subtitle, p); paths.append(p)

    if prior_sweep_dir is not None:
        prior = Path(prior_sweep_dir)
        df_prior = load.load_sweep(prior)
        label_prior = load.sweep_label(prior)

        p = plots_dir / "wall_vs_length_compare.png"
        _compare_metric_per_case(
            df, df_prior, label, label_prior,
            title="Wall time vs simulation length",
            ylabel="wall time (s)", column="wall",
            subtitle=subtitle, out_path=p, yscale="log",
        )
        paths.append(p)

        p = plots_dir / "per_step_vs_length_compare.png"
        _compare_metric_per_case(
            df, df_prior, label, label_prior,
            title="Per-step unaccounted gap vs simulation length",
            ylabel="per_step (ms)", column="per_step",
            subtitle=subtitle, out_path=p, yscale="linear",
            transform=lambda ys: ys * 1000.0,
        )
        paths.append(p)

    return paths


def _main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render perf-sweep plots.")
    p.add_argument("--sweep", required=True, help="Sweep directory to plot.")
    p.add_argument(
        "--prior",
        default=os.environ.get("PRIOR_SWEEP"),
        help="Optional prior-sweep directory for paired comparison plots.",
    )
    p.add_argument(
        "--out",
        default=None,
        help="Output directory (default: <sweep>/plots).",
    )
    args = p.parse_args(argv)
    paths = render(args.sweep, args.prior, args.out)
    for path in paths:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
